package com.example.cs202pzdopisivanje.Objects;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Message {
    private int id; // Auto-generated by database
    private int senderId;
    private int chatId;
    private String message;
    private String timeSent;

    // Constructor for creating new messages (without ID - will be auto-generated)
    public Message(int senderId, int chatId, String message) {
        this.senderId = senderId;
        this.chatId = chatId;
        this.message = message;
        this.timeSent = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    }

    // Constructor for messages retrieved from database (with ID)
    public Message(int id, int senderId, int chatId, String message, String timeSent) {
        this.id = id;
        this.senderId = senderId;
        this.chatId = chatId;
        this.message = message;
        this.timeSent = timeSent;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getSenderId() {
        return senderId;
    }

    public void setSenderId(int senderId) {
        this.senderId = senderId;
    }

    public int getChatId() {
        return chatId;
    }

    public void setChatId(int chatId) {
        this.chatId = chatId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getTimeSent() {
        return timeSent;
    }

    public void setTimeSent(String timeSent) {
        this.timeSent = timeSent;
    }
}