package com.example.cs202pzdopisivanje.Objects;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Message implements Serializable {
    private int id; // Auto-generated by database
    private String username;
    private int chatId;
    private String message;
    private String timeSent;

    // Constructor for creating new messages (without ID - will be auto-generated)
    public Message(String username, int chatId, String message) {
        this.username = username;
        this.chatId = chatId;
        this.message = message;
        this.timeSent = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    }

    // Constructor for messages retrieved from database (with ID)
    public Message(int id, String username, int chatId, String message, String timeSent) {
        this.id = id;
        this.username = username;
        this.chatId = chatId;
        this.message = message;
        this.timeSent = timeSent;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getChatId() {
        return chatId;
    }

    public void setChatId(int chatId) {
        this.chatId = chatId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getTimeSent() {
        return timeSent;
    }

    public void setTimeSent(String timeSent) {
        this.timeSent = timeSent;
    }
}